// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countMigrationLogs = `-- name: CountMigrationLogs :one
SELECT COUNT(*) FROM migration_log
`

func (q *Queries) CountMigrationLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMigrationLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDrive = `-- name: CreateDrive :one
INSERT INTO drive (device, mountpoint, fstype, total_gb, free_gb, used_pct)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, device, mountpoint, fstype, total_gb, free_gb, used_pct, created_at
`

type CreateDriveParams struct {
	Device     string  `json:"device"`
	Mountpoint string  `json:"mountpoint"`
	Fstype     string  `json:"fstype"`
	TotalGb    int64   `json:"total_gb"`
	FreeGb     int64   `json:"free_gb"`
	UsedPct    float64 `json:"used_pct"`
}

func (q *Queries) CreateDrive(ctx context.Context, arg CreateDriveParams) (Drive, error) {
	row := q.db.QueryRowContext(ctx, createDrive,
		arg.Device,
		arg.Mountpoint,
		arg.Fstype,
		arg.TotalGb,
		arg.FreeGb,
		arg.UsedPct,
	)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Device,
		&i.Mountpoint,
		&i.Fstype,
		&i.TotalGb,
		&i.FreeGb,
		&i.UsedPct,
		&i.CreatedAt,
	)
	return i, err
}

const createMigrationJob = `-- name: CreateMigrationJob :one
INSERT INTO migration_job (id, app_name, status)
VALUES (?, ?, ?)
RETURNING id, app_name, status, created_at, updated_at
`

type CreateMigrationJobParams struct {
	ID      string `json:"id"`
	AppName string `json:"app_name"`
	Status  string `json:"status"`
}

func (q *Queries) CreateMigrationJob(ctx context.Context, arg CreateMigrationJobParams) (MigrationJob, error) {
	row := q.db.QueryRowContext(ctx, createMigrationJob, arg.ID, arg.AppName, arg.Status)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMigrationLog = `-- name: CreateMigrationLog :one
INSERT INTO migration_log (job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at, created_at
`

type CreateMigrationLogParams struct {
	JobID        string         `json:"job_id"`
	AppName      string         `json:"app_name"`
	VolumeName   string         `json:"volume_name"`
	SourcePath   string         `json:"source_path"`
	SourceDrive  sql.NullString `json:"source_drive"`
	DestPath     string         `json:"dest_path"`
	DestDrive    string         `json:"dest_drive"`
	TotalBytes   int64          `json:"total_bytes"`
	DurationMs   int64          `json:"duration_ms"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
}

func (q *Queries) CreateMigrationLog(ctx context.Context, arg CreateMigrationLogParams) (MigrationLog, error) {
	row := q.db.QueryRowContext(ctx, createMigrationLog,
		arg.JobID,
		arg.AppName,
		arg.VolumeName,
		arg.SourcePath,
		arg.SourceDrive,
		arg.DestPath,
		arg.DestDrive,
		arg.TotalBytes,
		arg.DurationMs,
		arg.Status,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i MigrationLog
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AppName,
		&i.VolumeName,
		&i.SourcePath,
		&i.SourceDrive,
		&i.DestPath,
		&i.DestDrive,
		&i.TotalBytes,
		&i.DurationMs,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStatsBatch = `-- name: CreateStatsBatch :one
INSERT INTO stats_batch DEFAULT VALUES RETURNING id, captured_at
`

func (q *Queries) CreateStatsBatch(ctx context.Context) (StatsBatch, error) {
	row := q.db.QueryRowContext(ctx, createStatsBatch)
	var i StatsBatch
	err := row.Scan(&i.ID, &i.CapturedAt)
	return i, err
}

const createStatsDrive = `-- name: CreateStatsDrive :exec
INSERT INTO stats_drive (batch_id, mountpoint, device, total_bytes, used_bytes, free_bytes, duration_ms)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateStatsDriveParams struct {
	BatchID    int64  `json:"batch_id"`
	Mountpoint string `json:"mountpoint"`
	Device     string `json:"device"`
	TotalBytes int64  `json:"total_bytes"`
	UsedBytes  int64  `json:"used_bytes"`
	FreeBytes  int64  `json:"free_bytes"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) CreateStatsDrive(ctx context.Context, arg CreateStatsDriveParams) error {
	_, err := q.db.ExecContext(ctx, createStatsDrive,
		arg.BatchID,
		arg.Mountpoint,
		arg.Device,
		arg.TotalBytes,
		arg.UsedBytes,
		arg.FreeBytes,
		arg.DurationMs,
	)
	return err
}

const createStatsVolume = `-- name: CreateStatsVolume :exec
INSERT INTO stats_volume (batch_id, volume_name, container_name, source_path, total_bytes, duration_ms)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateStatsVolumeParams struct {
	BatchID       int64  `json:"batch_id"`
	VolumeName    string `json:"volume_name"`
	ContainerName string `json:"container_name"`
	SourcePath    string `json:"source_path"`
	TotalBytes    int64  `json:"total_bytes"`
	DurationMs    int64  `json:"duration_ms"`
}

func (q *Queries) CreateStatsVolume(ctx context.Context, arg CreateStatsVolumeParams) error {
	_, err := q.db.ExecContext(ctx, createStatsVolume,
		arg.BatchID,
		arg.VolumeName,
		arg.ContainerName,
		arg.SourcePath,
		arg.TotalBytes,
		arg.DurationMs,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, role, password_change_required)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, username, password_hash, role, password_change_required, created_at, updated_at
`

type CreateUserParams struct {
	Email                  sql.NullString `json:"email"`
	Username               string         `json:"username"`
	PasswordHash           string         `json:"password_hash"`
	Role                   string         `json:"role"`
	PasswordChangeRequired int64          `json:"password_change_required"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.PasswordChangeRequired,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PasswordChangeRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVolume = `-- name: CreateVolume :one
INSERT INTO volume (container_name, type, source, destination)
VALUES (?, ?, ?, ?)
RETURNING id, container_name, type, source, destination, created_at
`

type CreateVolumeParams struct {
	ContainerName string `json:"container_name"`
	Type          string `json:"type"`
	Source        string `json:"source"`
	Destination   string `json:"destination"`
}

func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, createVolume,
		arg.ContainerName,
		arg.Type,
		arg.Source,
		arg.Destination,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ContainerName,
		&i.Type,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}

const createVolumeDrive = `-- name: CreateVolumeDrive :one
INSERT INTO volume_drive (volume_id, drive_id)
VALUES (?, ?)
RETURNING id, volume_id, drive_id, created_at
`

type CreateVolumeDriveParams struct {
	VolumeID int64 `json:"volume_id"`
	DriveID  int64 `json:"drive_id"`
}

func (q *Queries) CreateVolumeDrive(ctx context.Context, arg CreateVolumeDriveParams) (VolumeDrive, error) {
	row := q.db.QueryRowContext(ctx, createVolumeDrive, arg.VolumeID, arg.DriveID)
	var i VolumeDrive
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.DriveID,
		&i.CreatedAt,
	)
	return i, err
}

const createVolumeProgress = `-- name: CreateVolumeProgress :one
INSERT INTO migration_volume_progress (job_id, volume_name, source_path, dest_path, dest_drive, step)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, volume_name, source_path, dest_path, dest_drive, step, total_bytes, transferred_bytes, error_message, created_at, updated_at
`

type CreateVolumeProgressParams struct {
	JobID      string `json:"job_id"`
	VolumeName string `json:"volume_name"`
	SourcePath string `json:"source_path"`
	DestPath   string `json:"dest_path"`
	DestDrive  string `json:"dest_drive"`
	Step       string `json:"step"`
}

func (q *Queries) CreateVolumeProgress(ctx context.Context, arg CreateVolumeProgressParams) (MigrationVolumeProgress, error) {
	row := q.db.QueryRowContext(ctx, createVolumeProgress,
		arg.JobID,
		arg.VolumeName,
		arg.SourcePath,
		arg.DestPath,
		arg.DestDrive,
		arg.Step,
	)
	var i MigrationVolumeProgress
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VolumeName,
		&i.SourcePath,
		&i.DestPath,
		&i.DestDrive,
		&i.Step,
		&i.TotalBytes,
		&i.TransferredBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDrive = `-- name: DeleteDrive :exec
DELETE FROM drive WHERE id = ?
`

func (q *Queries) DeleteDrive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDrive, id)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteMigrationLog = `-- name: DeleteMigrationLog :exec
DELETE FROM migration_log WHERE id = ?
`

func (q *Queries) DeleteMigrationLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMigrationLog, id)
	return err
}

const deleteOldStatsDrive = `-- name: DeleteOldStatsDrive :exec
DELETE FROM stats_drive WHERE captured_at < ?
`

func (q *Queries) DeleteOldStatsDrive(ctx context.Context, capturedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldStatsDrive, capturedAt)
	return err
}

const deleteOldStatsVolume = `-- name: DeleteOldStatsVolume :exec
DELETE FROM stats_volume WHERE captured_at < ?
`

func (q *Queries) DeleteOldStatsVolume(ctx context.Context, capturedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldStatsVolume, capturedAt)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_tokens WHERE user_id = ?
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserRefreshTokens, userID)
	return err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM volume WHERE id = ?
`

func (q *Queries) DeleteVolume(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVolume, id)
	return err
}

const deleteVolumeDrive = `-- name: DeleteVolumeDrive :exec
DELETE FROM volume_drive WHERE id = ?
`

func (q *Queries) DeleteVolumeDrive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVolumeDrive, id)
	return err
}

const getDrive = `-- name: GetDrive :one
SELECT id, device, mountpoint, fstype, total_gb, free_gb, used_pct, created_at FROM drive WHERE id = ?
`

func (q *Queries) GetDrive(ctx context.Context, id int64) (Drive, error) {
	row := q.db.QueryRowContext(ctx, getDrive, id)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Device,
		&i.Mountpoint,
		&i.Fstype,
		&i.TotalGb,
		&i.FreeGb,
		&i.UsedPct,
		&i.CreatedAt,
	)
	return i, err
}

const getMigrationJob = `-- name: GetMigrationJob :one
SELECT id, app_name, status, created_at, updated_at FROM migration_job WHERE id = ?
`

func (q *Queries) GetMigrationJob(ctx context.Context, id string) (MigrationJob, error) {
	row := q.db.QueryRowContext(ctx, getMigrationJob, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationLogByJobID = `-- name: GetMigrationLogByJobID :many
SELECT id, job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at, created_at FROM migration_log WHERE job_id = ? ORDER BY id
`

func (q *Queries) GetMigrationLogByJobID(ctx context.Context, jobID string) ([]MigrationLog, error) {
	rows, err := q.db.QueryContext(ctx, getMigrationLogByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationLog
	for rows.Next() {
		var i MigrationLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AppName,
			&i.VolumeName,
			&i.SourcePath,
			&i.SourceDrive,
			&i.DestPath,
			&i.DestDrive,
			&i.TotalBytes,
			&i.DurationMs,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMigrationStats = `-- name: GetMigrationStats :one
SELECT
  CAST(COUNT(*) AS INTEGER) as total_count,
  CAST(COALESCE(SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END), 0) AS INTEGER) as completed_count,
  CAST(COALESCE(SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END), 0) AS INTEGER) as failed_count,
  CAST(COALESCE(SUM(total_bytes), 0) AS INTEGER) as total_bytes_moved,
  CAST(COALESCE(SUM(duration_ms), 0) AS INTEGER) as total_duration_ms,
  CAST(COUNT(DISTINCT app_name) AS INTEGER) as unique_apps
FROM migration_log
`

type GetMigrationStatsRow struct {
	TotalCount      int64 `json:"total_count"`
	CompletedCount  int64 `json:"completed_count"`
	FailedCount     int64 `json:"failed_count"`
	TotalBytesMoved int64 `json:"total_bytes_moved"`
	TotalDurationMs int64 `json:"total_duration_ms"`
	UniqueApps      int64 `json:"unique_apps"`
}

func (q *Queries) GetMigrationStats(ctx context.Context) (GetMigrationStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getMigrationStats)
	var i GetMigrationStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.TotalBytesMoved,
		&i.TotalDurationMs,
		&i.UniqueApps,
	)
	return i, err
}

const getPreference = `-- name: GetPreference :one
SELECT "key", value FROM user_preferences WHERE key = ?
`

func (q *Queries) GetPreference(ctx context.Context, key string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getPreference, key)
	var i UserPreference
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, expires_at, created_at FROM refresh_tokens WHERE token = ?
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, role, password_change_required, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PasswordChangeRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, role, password_change_required, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PasswordChangeRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, role, password_change_required, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.PasswordChangeRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolume = `-- name: GetVolume :one
SELECT id, container_name, type, source, destination, created_at FROM volume WHERE id = ?
`

func (q *Queries) GetVolume(ctx context.Context, id int64) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolume, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ContainerName,
		&i.Type,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}

const getVolumeDrive = `-- name: GetVolumeDrive :one
SELECT id, volume_id, drive_id, created_at FROM volume_drive WHERE id = ?
`

func (q *Queries) GetVolumeDrive(ctx context.Context, id int64) (VolumeDrive, error) {
	row := q.db.QueryRowContext(ctx, getVolumeDrive, id)
	var i VolumeDrive
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.DriveID,
		&i.CreatedAt,
	)
	return i, err
}

const listDistinctAppNames = `-- name: ListDistinctAppNames :many
SELECT DISTINCT app_name FROM migration_log ORDER BY app_name
`

func (q *Queries) ListDistinctAppNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctAppNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var app_name string
		if err := rows.Scan(&app_name); err != nil {
			return nil, err
		}
		items = append(items, app_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrives = `-- name: ListDrives :many
SELECT id, device, mountpoint, fstype, total_gb, free_gb, used_pct, created_at FROM drive ORDER BY mountpoint
`

func (q *Queries) ListDrives(ctx context.Context) ([]Drive, error) {
	rows, err := q.db.QueryContext(ctx, listDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drive
	for rows.Next() {
		var i Drive
		if err := rows.Scan(
			&i.ID,
			&i.Device,
			&i.Mountpoint,
			&i.Fstype,
			&i.TotalGb,
			&i.FreeGb,
			&i.UsedPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsWithProgress = `-- name: ListJobsWithProgress :many
SELECT
    j.id AS job_id,
    j.app_name,
    j.status,
    j.created_at AS job_created_at,
    j.updated_at AS job_updated_at,
    p.id AS progress_id,
    p.job_id AS p_job_id,
    p.volume_name,
    p.source_path,
    p.dest_path,
    p.dest_drive,
    p.step,
    p.total_bytes,
    p.transferred_bytes,
    p.error_message,
    p.created_at AS progress_created_at,
    p.updated_at AS progress_updated_at
FROM migration_job j
JOIN migration_volume_progress p ON p.job_id = j.id
ORDER BY j.created_at DESC, p.id
`

type ListJobsWithProgressRow struct {
	JobID             string         `json:"job_id"`
	AppName           string         `json:"app_name"`
	Status            string         `json:"status"`
	JobCreatedAt      sql.NullTime   `json:"job_created_at"`
	JobUpdatedAt      sql.NullTime   `json:"job_updated_at"`
	ProgressID        int64          `json:"progress_id"`
	PJobID            string         `json:"p_job_id"`
	VolumeName        string         `json:"volume_name"`
	SourcePath        string         `json:"source_path"`
	DestPath          string         `json:"dest_path"`
	DestDrive         string         `json:"dest_drive"`
	Step              string         `json:"step"`
	TotalBytes        int64          `json:"total_bytes"`
	TransferredBytes  int64          `json:"transferred_bytes"`
	ErrorMessage      sql.NullString `json:"error_message"`
	ProgressCreatedAt sql.NullTime   `json:"progress_created_at"`
	ProgressUpdatedAt sql.NullTime   `json:"progress_updated_at"`
}

func (q *Queries) ListJobsWithProgress(ctx context.Context) ([]ListJobsWithProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsWithProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsWithProgressRow
	for rows.Next() {
		var i ListJobsWithProgressRow
		if err := rows.Scan(
			&i.JobID,
			&i.AppName,
			&i.Status,
			&i.JobCreatedAt,
			&i.JobUpdatedAt,
			&i.ProgressID,
			&i.PJobID,
			&i.VolumeName,
			&i.SourcePath,
			&i.DestPath,
			&i.DestDrive,
			&i.Step,
			&i.TotalBytes,
			&i.TransferredBytes,
			&i.ErrorMessage,
			&i.ProgressCreatedAt,
			&i.ProgressUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationJobs = `-- name: ListMigrationJobs :many
SELECT id, app_name, status, created_at, updated_at FROM migration_job ORDER BY created_at DESC
`

func (q *Queries) ListMigrationJobs(ctx context.Context) ([]MigrationJob, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationJob
	for rows.Next() {
		var i MigrationJob
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationLogs = `-- name: ListMigrationLogs :many
SELECT id, job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at, created_at FROM migration_log
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListMigrationLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMigrationLogs(ctx context.Context, arg ListMigrationLogsParams) ([]MigrationLog, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationLog
	for rows.Next() {
		var i MigrationLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AppName,
			&i.VolumeName,
			&i.SourcePath,
			&i.SourceDrive,
			&i.DestPath,
			&i.DestDrive,
			&i.TotalBytes,
			&i.DurationMs,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationLogsByApp = `-- name: ListMigrationLogsByApp :many
SELECT id, job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at, created_at FROM migration_log
WHERE app_name = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListMigrationLogsByAppParams struct {
	AppName string `json:"app_name"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListMigrationLogsByApp(ctx context.Context, arg ListMigrationLogsByAppParams) ([]MigrationLog, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationLogsByApp, arg.AppName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationLog
	for rows.Next() {
		var i MigrationLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AppName,
			&i.VolumeName,
			&i.SourcePath,
			&i.SourceDrive,
			&i.DestPath,
			&i.DestDrive,
			&i.TotalBytes,
			&i.DurationMs,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationLogsByDrive = `-- name: ListMigrationLogsByDrive :many
SELECT id, job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at, created_at FROM migration_log
WHERE dest_drive = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListMigrationLogsByDriveParams struct {
	DestDrive string `json:"dest_drive"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListMigrationLogsByDrive(ctx context.Context, arg ListMigrationLogsByDriveParams) ([]MigrationLog, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationLogsByDrive, arg.DestDrive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationLog
	for rows.Next() {
		var i MigrationLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AppName,
			&i.VolumeName,
			&i.SourcePath,
			&i.SourceDrive,
			&i.DestPath,
			&i.DestDrive,
			&i.TotalBytes,
			&i.DurationMs,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationLogsByStatus = `-- name: ListMigrationLogsByStatus :many
SELECT id, job_id, app_name, volume_name, source_path, source_drive, dest_path, dest_drive, total_bytes, duration_ms, status, error_message, started_at, completed_at, created_at FROM migration_log
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListMigrationLogsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMigrationLogsByStatus(ctx context.Context, arg ListMigrationLogsByStatusParams) ([]MigrationLog, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationLogsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationLog
	for rows.Next() {
		var i MigrationLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AppName,
			&i.VolumeName,
			&i.SourcePath,
			&i.SourceDrive,
			&i.DestPath,
			&i.DestDrive,
			&i.TotalBytes,
			&i.DurationMs,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferences = `-- name: ListPreferences :many
SELECT "key", value FROM user_preferences
`

func (q *Queries) ListPreferences(ctx context.Context) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatsApplication = `-- name: ListStatsApplication :many
SELECT
    s.captured_at,
    s.container_name,
    SUM(s.total_bytes) AS total_bytes
FROM stats_volume s
WHERE s.container_name = ? AND s.captured_at >= ? AND s.captured_at <= ?
GROUP BY s.batch_id, s.container_name
ORDER BY s.captured_at
`

type ListStatsApplicationParams struct {
	ContainerName string    `json:"container_name"`
	CapturedAt    time.Time `json:"captured_at"`
	CapturedAt_2  time.Time `json:"captured_at_2"`
}

type ListStatsApplicationRow struct {
	CapturedAt    time.Time       `json:"captured_at"`
	ContainerName string          `json:"container_name"`
	TotalBytes    sql.NullFloat64 `json:"total_bytes"`
}

func (q *Queries) ListStatsApplication(ctx context.Context, arg ListStatsApplicationParams) ([]ListStatsApplicationRow, error) {
	rows, err := q.db.QueryContext(ctx, listStatsApplication, arg.ContainerName, arg.CapturedAt, arg.CapturedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatsApplicationRow
	for rows.Next() {
		var i ListStatsApplicationRow
		if err := rows.Scan(&i.CapturedAt, &i.ContainerName, &i.TotalBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatsDriveByMountpoint = `-- name: ListStatsDriveByMountpoint :many
SELECT id, batch_id, mountpoint, device, total_bytes, used_bytes, free_bytes, duration_ms, captured_at FROM stats_drive
WHERE mountpoint = ? AND captured_at >= ? AND captured_at <= ?
ORDER BY captured_at
`

type ListStatsDriveByMountpointParams struct {
	Mountpoint   string    `json:"mountpoint"`
	CapturedAt   time.Time `json:"captured_at"`
	CapturedAt_2 time.Time `json:"captured_at_2"`
}

func (q *Queries) ListStatsDriveByMountpoint(ctx context.Context, arg ListStatsDriveByMountpointParams) ([]StatsDrive, error) {
	rows, err := q.db.QueryContext(ctx, listStatsDriveByMountpoint, arg.Mountpoint, arg.CapturedAt, arg.CapturedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsDrive
	for rows.Next() {
		var i StatsDrive
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Mountpoint,
			&i.Device,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.DurationMs,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatsVolumeByName = `-- name: ListStatsVolumeByName :many
SELECT id, batch_id, volume_name, container_name, source_path, total_bytes, duration_ms, captured_at FROM stats_volume
WHERE volume_name = ? AND captured_at >= ? AND captured_at <= ?
ORDER BY captured_at
`

type ListStatsVolumeByNameParams struct {
	VolumeName   string    `json:"volume_name"`
	CapturedAt   time.Time `json:"captured_at"`
	CapturedAt_2 time.Time `json:"captured_at_2"`
}

func (q *Queries) ListStatsVolumeByName(ctx context.Context, arg ListStatsVolumeByNameParams) ([]StatsVolume, error) {
	rows, err := q.db.QueryContext(ctx, listStatsVolumeByName, arg.VolumeName, arg.CapturedAt, arg.CapturedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsVolume
	for rows.Next() {
		var i StatsVolume
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.VolumeName,
			&i.ContainerName,
			&i.SourcePath,
			&i.TotalBytes,
			&i.DurationMs,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, role, password_change_required, created_at, updated_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.PasswordChangeRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeDrives = `-- name: ListVolumeDrives :many
SELECT
    vd.id,
    vd.volume_id,
    vd.drive_id,
    vd.created_at,
    v.container_name,
    v.type AS volume_type,
    v.source,
    v.destination,
    d.device,
    d.mountpoint,
    d.fstype,
    d.total_gb,
    d.free_gb,
    d.used_pct
FROM volume_drive vd
JOIN volume v ON v.id = vd.volume_id
JOIN drive d ON d.id = vd.drive_id
`

type ListVolumeDrivesRow struct {
	ID            int64        `json:"id"`
	VolumeID      int64        `json:"volume_id"`
	DriveID       int64        `json:"drive_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	ContainerName string       `json:"container_name"`
	VolumeType    string       `json:"volume_type"`
	Source        string       `json:"source"`
	Destination   string       `json:"destination"`
	Device        string       `json:"device"`
	Mountpoint    string       `json:"mountpoint"`
	Fstype        string       `json:"fstype"`
	TotalGb       int64        `json:"total_gb"`
	FreeGb        int64        `json:"free_gb"`
	UsedPct       float64      `json:"used_pct"`
}

func (q *Queries) ListVolumeDrives(ctx context.Context) ([]ListVolumeDrivesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVolumeDrivesRow
	for rows.Next() {
		var i ListVolumeDrivesRow
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.DriveID,
			&i.CreatedAt,
			&i.ContainerName,
			&i.VolumeType,
			&i.Source,
			&i.Destination,
			&i.Device,
			&i.Mountpoint,
			&i.Fstype,
			&i.TotalGb,
			&i.FreeGb,
			&i.UsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeProgressByJob = `-- name: ListVolumeProgressByJob :many
SELECT id, job_id, volume_name, source_path, dest_path, dest_drive, step, total_bytes, transferred_bytes, error_message, created_at, updated_at FROM migration_volume_progress WHERE job_id = ? ORDER BY id
`

func (q *Queries) ListVolumeProgressByJob(ctx context.Context, jobID string) ([]MigrationVolumeProgress, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeProgressByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationVolumeProgress
	for rows.Next() {
		var i MigrationVolumeProgress
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.VolumeName,
			&i.SourcePath,
			&i.DestPath,
			&i.DestDrive,
			&i.Step,
			&i.TotalBytes,
			&i.TransferredBytes,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT id, container_name, type, source, destination, created_at FROM volume ORDER BY container_name
`

func (q *Queries) ListVolumes(ctx context.Context) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.ContainerName,
			&i.Type,
			&i.Source,
			&i.Destination,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMigrationJobStatus = `-- name: UpdateMigrationJobStatus :exec
UPDATE migration_job SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateMigrationJobStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateMigrationJobStatus(ctx context.Context, arg UpdateMigrationJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMigrationJobStatus, arg.Status, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, password_change_required = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateVolumeProgressBytes = `-- name: UpdateVolumeProgressBytes :exec
UPDATE migration_volume_progress SET transferred_bytes = ?, total_bytes = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVolumeProgressBytesParams struct {
	TransferredBytes int64 `json:"transferred_bytes"`
	TotalBytes       int64 `json:"total_bytes"`
	ID               int64 `json:"id"`
}

func (q *Queries) UpdateVolumeProgressBytes(ctx context.Context, arg UpdateVolumeProgressBytesParams) error {
	_, err := q.db.ExecContext(ctx, updateVolumeProgressBytes, arg.TransferredBytes, arg.TotalBytes, arg.ID)
	return err
}

const updateVolumeProgressError = `-- name: UpdateVolumeProgressError :exec
UPDATE migration_volume_progress SET step = 'failed', error_message = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVolumeProgressErrorParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateVolumeProgressError(ctx context.Context, arg UpdateVolumeProgressErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateVolumeProgressError, arg.ErrorMessage, arg.ID)
	return err
}

const updateVolumeProgressStep = `-- name: UpdateVolumeProgressStep :exec
UPDATE migration_volume_progress SET step = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVolumeProgressStepParams struct {
	Step string `json:"step"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateVolumeProgressStep(ctx context.Context, arg UpdateVolumeProgressStepParams) error {
	_, err := q.db.ExecContext(ctx, updateVolumeProgressStep, arg.Step, arg.ID)
	return err
}

const upsertPreference = `-- name: UpsertPreference :exec
INSERT INTO user_preferences (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertPreferenceParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPreference, arg.Key, arg.Value)
	return err
}
