// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDrive(ctx context.Context, arg CreateDriveParams) (Drive, error)
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error)
	CreateVolumeDrive(ctx context.Context, arg CreateVolumeDriveParams) (VolumeDrive, error)
	DeleteDrive(ctx context.Context, id int64) error
	DeleteVolume(ctx context.Context, id int64) error
	DeleteVolumeDrive(ctx context.Context, id int64) error
	GetDrive(ctx context.Context, id int64) (Drive, error)
	GetVolume(ctx context.Context, id int64) (Volume, error)
	GetVolumeDrive(ctx context.Context, id int64) (VolumeDrive, error)
	ListDrives(ctx context.Context) ([]Drive, error)
	ListVolumeDrives(ctx context.Context) ([]ListVolumeDrivesRow, error)
	ListVolumes(ctx context.Context) ([]Volume, error)
}

var _ Querier = (*Queries)(nil)
