// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createDrive = `-- name: CreateDrive :one
INSERT INTO drive (device, mountpoint, fstype, total_gb, free_gb, used_pct)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, device, mountpoint, fstype, total_gb, free_gb, used_pct, created_at
`

type CreateDriveParams struct {
	Device     string  `json:"device"`
	Mountpoint string  `json:"mountpoint"`
	Fstype     string  `json:"fstype"`
	TotalGb    int64   `json:"total_gb"`
	FreeGb     int64   `json:"free_gb"`
	UsedPct    float64 `json:"used_pct"`
}

func (q *Queries) CreateDrive(ctx context.Context, arg CreateDriveParams) (Drive, error) {
	row := q.db.QueryRowContext(ctx, createDrive,
		arg.Device,
		arg.Mountpoint,
		arg.Fstype,
		arg.TotalGb,
		arg.FreeGb,
		arg.UsedPct,
	)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Device,
		&i.Mountpoint,
		&i.Fstype,
		&i.TotalGb,
		&i.FreeGb,
		&i.UsedPct,
		&i.CreatedAt,
	)
	return i, err
}

const createVolume = `-- name: CreateVolume :one
INSERT INTO volume (container_name, type, source, destination)
VALUES (?, ?, ?, ?)
RETURNING id, container_name, type, source, destination, created_at
`

type CreateVolumeParams struct {
	ContainerName string `json:"container_name"`
	Type          string `json:"type"`
	Source        string `json:"source"`
	Destination   string `json:"destination"`
}

func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, createVolume,
		arg.ContainerName,
		arg.Type,
		arg.Source,
		arg.Destination,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ContainerName,
		&i.Type,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}

const createVolumeDrive = `-- name: CreateVolumeDrive :one
INSERT INTO volume_drive (volume_id, drive_id)
VALUES (?, ?)
RETURNING id, volume_id, drive_id, created_at
`

type CreateVolumeDriveParams struct {
	VolumeID int64 `json:"volume_id"`
	DriveID  int64 `json:"drive_id"`
}

func (q *Queries) CreateVolumeDrive(ctx context.Context, arg CreateVolumeDriveParams) (VolumeDrive, error) {
	row := q.db.QueryRowContext(ctx, createVolumeDrive, arg.VolumeID, arg.DriveID)
	var i VolumeDrive
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.DriveID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDrive = `-- name: DeleteDrive :exec
DELETE FROM drive WHERE id = ?
`

func (q *Queries) DeleteDrive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDrive, id)
	return err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM volume WHERE id = ?
`

func (q *Queries) DeleteVolume(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVolume, id)
	return err
}

const deleteVolumeDrive = `-- name: DeleteVolumeDrive :exec
DELETE FROM volume_drive WHERE id = ?
`

func (q *Queries) DeleteVolumeDrive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVolumeDrive, id)
	return err
}

const getDrive = `-- name: GetDrive :one
SELECT id, device, mountpoint, fstype, total_gb, free_gb, used_pct, created_at FROM drive WHERE id = ?
`

func (q *Queries) GetDrive(ctx context.Context, id int64) (Drive, error) {
	row := q.db.QueryRowContext(ctx, getDrive, id)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Device,
		&i.Mountpoint,
		&i.Fstype,
		&i.TotalGb,
		&i.FreeGb,
		&i.UsedPct,
		&i.CreatedAt,
	)
	return i, err
}

const getVolume = `-- name: GetVolume :one
SELECT id, container_name, type, source, destination, created_at FROM volume WHERE id = ?
`

func (q *Queries) GetVolume(ctx context.Context, id int64) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolume, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ContainerName,
		&i.Type,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}

const getVolumeDrive = `-- name: GetVolumeDrive :one
SELECT id, volume_id, drive_id, created_at FROM volume_drive WHERE id = ?
`

func (q *Queries) GetVolumeDrive(ctx context.Context, id int64) (VolumeDrive, error) {
	row := q.db.QueryRowContext(ctx, getVolumeDrive, id)
	var i VolumeDrive
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.DriveID,
		&i.CreatedAt,
	)
	return i, err
}

const listDrives = `-- name: ListDrives :many
SELECT id, device, mountpoint, fstype, total_gb, free_gb, used_pct, created_at FROM drive ORDER BY mountpoint
`

func (q *Queries) ListDrives(ctx context.Context) ([]Drive, error) {
	rows, err := q.db.QueryContext(ctx, listDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drive
	for rows.Next() {
		var i Drive
		if err := rows.Scan(
			&i.ID,
			&i.Device,
			&i.Mountpoint,
			&i.Fstype,
			&i.TotalGb,
			&i.FreeGb,
			&i.UsedPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumeDrives = `-- name: ListVolumeDrives :many
SELECT
    vd.id,
    vd.volume_id,
    vd.drive_id,
    vd.created_at,
    v.container_name,
    v.type AS volume_type,
    v.source,
    v.destination,
    d.device,
    d.mountpoint,
    d.fstype,
    d.total_gb,
    d.free_gb,
    d.used_pct
FROM volume_drive vd
JOIN volume v ON v.id = vd.volume_id
JOIN drive d ON d.id = vd.drive_id
`

type ListVolumeDrivesRow struct {
	ID            int64        `json:"id"`
	VolumeID      int64        `json:"volume_id"`
	DriveID       int64        `json:"drive_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	ContainerName string       `json:"container_name"`
	VolumeType    string       `json:"volume_type"`
	Source        string       `json:"source"`
	Destination   string       `json:"destination"`
	Device        string       `json:"device"`
	Mountpoint    string       `json:"mountpoint"`
	Fstype        string       `json:"fstype"`
	TotalGb       int64        `json:"total_gb"`
	FreeGb        int64        `json:"free_gb"`
	UsedPct       float64      `json:"used_pct"`
}

func (q *Queries) ListVolumeDrives(ctx context.Context) ([]ListVolumeDrivesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVolumeDrivesRow
	for rows.Next() {
		var i ListVolumeDrivesRow
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.DriveID,
			&i.CreatedAt,
			&i.ContainerName,
			&i.VolumeType,
			&i.Source,
			&i.Destination,
			&i.Device,
			&i.Mountpoint,
			&i.Fstype,
			&i.TotalGb,
			&i.FreeGb,
			&i.UsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMigrationJob = `-- name: CreateMigrationJob :one
INSERT INTO migration_job (id, app_name, status)
VALUES (?, ?, ?)
RETURNING id, app_name, status, created_at, updated_at
`

type CreateMigrationJobParams struct {
	ID      string `json:"id"`
	AppName string `json:"app_name"`
	Status  string `json:"status"`
}

func (q *Queries) CreateMigrationJob(ctx context.Context, arg CreateMigrationJobParams) (MigrationJob, error) {
	row := q.db.QueryRowContext(ctx, createMigrationJob, arg.ID, arg.AppName, arg.Status)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationJob = `-- name: GetMigrationJob :one
SELECT id, app_name, status, created_at, updated_at FROM migration_job WHERE id = ?
`

func (q *Queries) GetMigrationJob(ctx context.Context, id string) (MigrationJob, error) {
	row := q.db.QueryRowContext(ctx, getMigrationJob, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMigrationJobs = `-- name: ListMigrationJobs :many
SELECT id, app_name, status, created_at, updated_at FROM migration_job ORDER BY created_at DESC
`

func (q *Queries) ListMigrationJobs(ctx context.Context) ([]MigrationJob, error) {
	rows, err := q.db.QueryContext(ctx, listMigrationJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationJob
	for rows.Next() {
		var i MigrationJob
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMigrationJobStatus = `-- name: UpdateMigrationJobStatus :exec
UPDATE migration_job SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateMigrationJobStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateMigrationJobStatus(ctx context.Context, arg UpdateMigrationJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMigrationJobStatus, arg.Status, arg.ID)
	return err
}

const createVolumeProgress = `-- name: CreateVolumeProgress :one
INSERT INTO migration_volume_progress (job_id, volume_name, source_path, dest_path, dest_drive, step)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, volume_name, source_path, dest_path, dest_drive, step, total_bytes, transferred_bytes, error_message, created_at, updated_at
`

type CreateVolumeProgressParams struct {
	JobID      string `json:"job_id"`
	VolumeName string `json:"volume_name"`
	SourcePath string `json:"source_path"`
	DestPath   string `json:"dest_path"`
	DestDrive  string `json:"dest_drive"`
	Step       string `json:"step"`
}

func (q *Queries) CreateVolumeProgress(ctx context.Context, arg CreateVolumeProgressParams) (MigrationVolumeProgress, error) {
	row := q.db.QueryRowContext(ctx, createVolumeProgress,
		arg.JobID,
		arg.VolumeName,
		arg.SourcePath,
		arg.DestPath,
		arg.DestDrive,
		arg.Step,
	)
	var i MigrationVolumeProgress
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VolumeName,
		&i.SourcePath,
		&i.DestPath,
		&i.DestDrive,
		&i.Step,
		&i.TotalBytes,
		&i.TransferredBytes,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVolumeProgressByJob = `-- name: ListVolumeProgressByJob :many
SELECT id, job_id, volume_name, source_path, dest_path, dest_drive, step, total_bytes, transferred_bytes, error_message, created_at, updated_at FROM migration_volume_progress WHERE job_id = ? ORDER BY id
`

func (q *Queries) ListVolumeProgressByJob(ctx context.Context, jobID string) ([]MigrationVolumeProgress, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeProgressByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationVolumeProgress
	for rows.Next() {
		var i MigrationVolumeProgress
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.VolumeName,
			&i.SourcePath,
			&i.DestPath,
			&i.DestDrive,
			&i.Step,
			&i.TotalBytes,
			&i.TransferredBytes,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVolumeProgressStep = `-- name: UpdateVolumeProgressStep :exec
UPDATE migration_volume_progress SET step = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVolumeProgressStepParams struct {
	Step string `json:"step"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateVolumeProgressStep(ctx context.Context, arg UpdateVolumeProgressStepParams) error {
	_, err := q.db.ExecContext(ctx, updateVolumeProgressStep, arg.Step, arg.ID)
	return err
}

const updateVolumeProgressBytes = `-- name: UpdateVolumeProgressBytes :exec
UPDATE migration_volume_progress SET transferred_bytes = ?, total_bytes = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVolumeProgressBytesParams struct {
	TransferredBytes int64 `json:"transferred_bytes"`
	TotalBytes       int64 `json:"total_bytes"`
	ID               int64 `json:"id"`
}

func (q *Queries) UpdateVolumeProgressBytes(ctx context.Context, arg UpdateVolumeProgressBytesParams) error {
	_, err := q.db.ExecContext(ctx, updateVolumeProgressBytes, arg.TransferredBytes, arg.TotalBytes, arg.ID)
	return err
}

const updateVolumeProgressError = `-- name: UpdateVolumeProgressError :exec
UPDATE migration_volume_progress SET step = 'failed', error_message = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateVolumeProgressErrorParams struct {
	ErrorMessage string `json:"error_message"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateVolumeProgressError(ctx context.Context, arg UpdateVolumeProgressErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateVolumeProgressError, arg.ErrorMessage, arg.ID)
	return err
}

const listVolumes = `-- name: ListVolumes :many
SELECT id, container_name, type, source, destination, created_at FROM volume ORDER BY container_name
`

func (q *Queries) ListVolumes(ctx context.Context) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.ContainerName,
			&i.Type,
			&i.Source,
			&i.Destination,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
