// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDrive(ctx context.Context, arg CreateDriveParams) (Drive, error)
	CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error)
	CreateVolumeDrive(ctx context.Context, arg CreateVolumeDriveParams) (VolumeDrive, error)
	DeleteDrive(ctx context.Context, id int64) error
	DeleteVolume(ctx context.Context, id int64) error
	DeleteVolumeDrive(ctx context.Context, id int64) error
	GetDrive(ctx context.Context, id int64) (Drive, error)
	GetVolume(ctx context.Context, id int64) (Volume, error)
	GetVolumeDrive(ctx context.Context, id int64) (VolumeDrive, error)
	ListDrives(ctx context.Context) ([]Drive, error)
	ListVolumeDrives(ctx context.Context) ([]ListVolumeDrivesRow, error)
	ListVolumes(ctx context.Context) ([]Volume, error)
	CreateMigrationJob(ctx context.Context, arg CreateMigrationJobParams) (MigrationJob, error)
	GetMigrationJob(ctx context.Context, id string) (MigrationJob, error)
	ListMigrationJobs(ctx context.Context) ([]MigrationJob, error)
	UpdateMigrationJobStatus(ctx context.Context, arg UpdateMigrationJobStatusParams) error
	CreateVolumeProgress(ctx context.Context, arg CreateVolumeProgressParams) (MigrationVolumeProgress, error)
	ListVolumeProgressByJob(ctx context.Context, jobID string) ([]MigrationVolumeProgress, error)
	UpdateVolumeProgressStep(ctx context.Context, arg UpdateVolumeProgressStepParams) error
	UpdateVolumeProgressBytes(ctx context.Context, arg UpdateVolumeProgressBytesParams) error
	UpdateVolumeProgressError(ctx context.Context, arg UpdateVolumeProgressErrorParams) error
	ListJobsWithProgress(ctx context.Context) ([]ListJobsWithProgressRow, error)
}

var _ Querier = (*Queries)(nil)
